# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_auto_20180522_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
