# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0004_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='asset_id',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='asset_id',
            new_name='asset',
        ),
    ]
