# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0007_auto_20180529_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='num',
            field=models.FloatField(default=0),
        ),
    ]
