# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0008_record_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
