# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0010_auto_20180604_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
