# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0013_packet_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='packetNo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
