# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0014_packet_packetno'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='userName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
