# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0016_packetrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetrecord',
            name='userName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
