# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0017_packetrecord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rebate',
            field=models.FloatField(default=0),
        ),
    ]
