# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0018_activity_rebate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_user_id', models.CharField(default='', max_length=200)),
                ('get_date', models.DateTimeField(auto_now_add=True, verbose_name='get candy')),
                ('rebate', models.FloatField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy.User')),
            ],
        ),
    ]
