# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0019_rebaterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebaterecord',
            name='get_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='get rebate'),
        ),
    ]
