# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0020_auto_20180614_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='deposit')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy.User')),
            ],
        ),
    ]
