# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0021_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='frozen',
            field=models.FloatField(default=0),
        ),
    ]
