# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0023_deposit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='userPic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
