# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0024_auto_20180615_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='admin_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
