# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0026_auto_20180615_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
