# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0027_asset_asset_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_source',
            field=models.CharField(default='', max_length=20),
        ),
    ]
