# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0028_asset_asset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_cny',
            field=models.FloatField(default=0),
        ),
    ]
